### ISSUE TITLE
Prepare schema for tables

### ISSUE THREAD

**Issue by Gadheyan** [Gadheyan/DigiBill#2]
Prepare the schema for client,invoice,products etc.,

**Comment by maneeshakp** [comment]
[schema.docx](https://github.com/Gadheyan/DigiBill/files/200706/schema.docx)

**Comment by Gadheyan** [comment]
I am not able to see the schema in libre office. Can you send a pdf version of it?

**Comment by maneeshakp** [comment]
ok the pdf is attatched.
[schema.pdf](https://github.com/Gadheyan/DigiBill/files/200827/schema.pdf)

**Comment by Gadheyan** [comment]
In the owner details, a column for logo should be added. The type can be BLOB.
Also Is there a need of auto-increment id for owner details since there is only one owner.
